import { NATIVE_LANG } from "./config";

export interface Language {
  code: string;
  name: string;
  flag: string;
}

/** Listener's choice for "no translation, hear everyone natively." */
export const NATIVE_OPTION: Language = {
  code: NATIVE_LANG,
  name: "None — Native",
  flag: "👂",
};

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: "ab", name: "Abkhaz", flag: "🌍" },
  { code: "ace", name: "Acehnese", flag: "🌍" },
  { code: "ach", name: "Acholi", flag: "🌍" },
  { code: "aa", name: "Afar", flag: "🌍" },
  { code: "af", name: "Afrikaans", flag: "🇿🇦" },
  { code: "sq", name: "Albanian", flag: "🇦🇱" },
  { code: "alz", name: "Alur", flag: "🌍" },
  { code: "am", name: "Amharic", flag: "🇪🇹" },
  { code: "ar", name: "Arabic", flag: "🇸🇦" },
  { code: "hy", name: "Armenian", flag: "🇦🇲" },
  { code: "as", name: "Assamese", flag: "🇮🇳" },
  { code: "av", name: "Avar", flag: "🌍" },
  { code: "awa", name: "Awadhi", flag: "🌍" },
  { code: "ay", name: "Aymara", flag: "🇧🇴" },
  { code: "az", name: "Azerbaijani", flag: "🇦🇿" },
  { code: "ban", name: "Balinese", flag: "🌍" },
  { code: "bal", name: "Baluchi", flag: "🌍" },
  { code: "bm", name: "Bambara", flag: "🇲🇱" },
  { code: "bci", name: "Baoulé", flag: "🌍" },
  { code: "ba", name: "Bashkir", flag: "🌍" },
  { code: "eu", name: "Basque", flag: "🇪🇸" },
  { code: "btx", name: "Batak Karo", flag: "🌍" },
  { code: "bts", name: "Batak Simalungun", flag: "🌍" },
  { code: "bbc", name: "Batak Toba", flag: "🌍" },
  { code: "be", name: "Belarusian", flag: "🇧🇾" },
  { code: "bem", name: "Bemba", flag: "🌍" },
  { code: "bn", name: "Bengali", flag: "🇧🇩" },
  { code: "bew", name: "Betawi", flag: "🌍" },
  { code: "bho", name: "Bhojpuri", flag: "🇮🇳" },
  { code: "bik", name: "Bikol", flag: "🌍" },
  { code: "bs", name: "Bosnian", flag: "🇧🇦" },
  { code: "br", name: "Breton", flag: "🌍" },
  { code: "bg", name: "Bulgarian", flag: "🇧🇬" },
  { code: "bua", name: "Buryat", flag: "🌍" },
  { code: "yue", name: "Cantonese", flag: "🇭🇰" },
  { code: "ca", name: "Catalan", flag: "🇪🇸" },
  { code: "ceb", name: "Cebuano", flag: "🇵🇭" },
  { code: "ch", name: "Chamorro", flag: "🌍" },
  { code: "ce", name: "Chechen", flag: "🌍" },
  { code: "ny", name: "Chichewa", flag: "🌍" },
  { code: "zh-CN", name: "Chinese (Simplified)", flag: "🇨🇳" },
  { code: "zh-TW", name: "Chinese (Traditional)", flag: "🇹🇼" },
  { code: "chk", name: "Chuukese", flag: "🌍" },
  { code: "cv", name: "Chuvash", flag: "🌍" },
  { code: "co", name: "Corsican", flag: "🇫🇷" },
  { code: "crh-Cyrl", name: "Crimean Tatar (Cyrillic)", flag: "🌍" },
  { code: "crh-Latn", name: "Crimean Tatar (Latin)", flag: "🌍" },
  { code: "hr", name: "Croatian", flag: "🇭🇷" },
  { code: "cs", name: "Czech", flag: "🇨🇿" },
  { code: "da", name: "Danish", flag: "🇩🇰" },
  { code: "prs", name: "Dari", flag: "🌍" },
  { code: "dv", name: "Dhivehi", flag: "🇲🇻" },
  { code: "din", name: "Dinka", flag: "🌍" },
  { code: "doi", name: "Dogri", flag: "🇮🇳" },
  { code: "dov", name: "Dombe", flag: "🌍" },
  { code: "nl", name: "Dutch", flag: "🇳🇱" },
  { code: "nl-BE", name: "Flemish (Belgian Dutch)", flag: "🇧🇪" },
  { code: "dyu", name: "Dyula", flag: "🌍" },
  { code: "dz", name: "Dzongkha", flag: "🌍" },
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "eo", name: "Esperanto", flag: "🌍" },
  { code: "et", name: "Estonian", flag: "🇪🇪" },
  { code: "ee", name: "Ewe", flag: "🇬🇭" },
  { code: "fo", name: "Faroese", flag: "🇫🇴" },
  { code: "fj", name: "Fijian", flag: "🇫🇯" },
  { code: "tl", name: "Filipino", flag: "🇵🇭" },
  { code: "fi", name: "Finnish", flag: "🇫🇮" },
  { code: "fon", name: "Fon", flag: "🌍" },
  { code: "fr", name: "French", flag: "🇫🇷" },
  { code: "fr-CA", name: "French (Canada)", flag: "🇨🇦" },
  { code: "fy", name: "Frisian", flag: "🇳🇱" },
  { code: "fur", name: "Friulian", flag: "🌍" },
  { code: "ff", name: "Fulani", flag: "🌍" },
  { code: "gaa", name: "Ga", flag: "🌍" },
  { code: "gl", name: "Galician", flag: "🇪🇸" },
  { code: "ka", name: "Georgian", flag: "🇬🇪" },
  { code: "de", name: "German", flag: "🇩🇪" },
  { code: "el", name: "Greek", flag: "🇬🇷" },
  { code: "gn", name: "Guarani", flag: "🇵🇾" },
  { code: "gu", name: "Gujarati", flag: "🇮🇳" },
  { code: "ht", name: "Haitian Creole", flag: "🇭🇹" },
  { code: "cnh", name: "Hakha Chin", flag: "🌍" },
  { code: "ha", name: "Hausa", flag: "🇳🇬" },
  { code: "haw", name: "Hawaiian", flag: "🇺🇸" },
  { code: "he", name: "Hebrew", flag: "🇮🇱" },
  { code: "hil", name: "Hiligaynon", flag: "🌍" },
  { code: "hi", name: "Hindi", flag: "🇮🇳" },
  { code: "hmn", name: "Hmong", flag: "🇨🇳" },
  { code: "hu", name: "Hungarian", flag: "🇭🇺" },
  { code: "hrx", name: "Hunsrik", flag: "🌍" },
  { code: "iba", name: "Iban", flag: "🌍" },
  { code: "is", name: "Icelandic", flag: "🇮🇸" },
  { code: "ig", name: "Igbo", flag: "🇳🇬" },
  { code: "ilo", name: "Ilocano", flag: "🇵🇭" },
  { code: "id", name: "Indonesian", flag: "🇮🇩" },
  { code: "iu-Latn", name: "Inuktut (Latin)", flag: "🌍" },
  { code: "iu-Cans", name: "Inuktut (Syllabics)", flag: "🌍" },
  { code: "ga", name: "Irish", flag: "🇮🇪" },
  { code: "it", name: "Italian", flag: "🇮🇹" },
  { code: "jam", name: "Jamaican Patois", flag: "🌍" },
  { code: "ja", name: "Japanese", flag: "🇯🇵" },
  { code: "jv", name: "Javanese", flag: "🇮🇩" },
  { code: "kac", name: "Jingpo", flag: "🌍" },
  { code: "kl", name: "Kalaallisut", flag: "🌍" },
  { code: "kn", name: "Kannada", flag: "🇮🇳" },
  { code: "kr", name: "Kanuri", flag: "🌍" },
  { code: "pam", name: "Kapampangan", flag: "🌍" },
  { code: "kk", name: "Kazakh", flag: "🇰🇿" },
  { code: "kha", name: "Khasi", flag: "🌍" },
  { code: "km", name: "Khmer", flag: "🇰🇭" },
  { code: "cgg", name: "Kiga", flag: "🌍" },
  { code: "kg", name: "Kikongo", flag: "🌍" },
  { code: "rw", name: "Kinyarwanda", flag: "🇷🇼" },
  { code: "ktu", name: "Kituba", flag: "🌍" },
  { code: "trp", name: "Kokborok", flag: "🌍" },
  { code: "kv", name: "Komi", flag: "🌍" },
  { code: "kok", name: "Konkani", flag: "🇮🇳" },
  { code: "ko", name: "Korean", flag: "🇰🇷" },
  { code: "kri", name: "Krio", flag: "🇸🇱" },
  { code: "ku", name: "Kurdish (Kurmanji)", flag: "🇹🇷" },
  { code: "ckb", name: "Kurdish (Sorani)", flag: "🇮🇶" },
  { code: "ky", name: "Kyrgyz", flag: "🇰🇬" },
  { code: "lo", name: "Lao", flag: "🇱🇦" },
  { code: "ltg", name: "Latgalian", flag: "🌍" },
  { code: "la", name: "Latin", flag: "🇻🇦" },
  { code: "lv", name: "Latvian", flag: "🇱🇻" },
  { code: "lij", name: "Ligurian", flag: "🌍" },
  { code: "li", name: "Limburgish", flag: "🌍" },
  { code: "ln", name: "Lingala", flag: "🇨🇩" },
  { code: "lt", name: "Lithuanian", flag: "🇱🇹" },
  { code: "lmo", name: "Lombard", flag: "🌍" },
  { code: "lg", name: "Luganda", flag: "🇺🇬" },
  { code: "luo", name: "Luo", flag: "🌍" },
  { code: "lb", name: "Luxembourgish", flag: "🇱🇺" },
  { code: "mk", name: "Macedonian", flag: "🇲🇰" },
  { code: "mad", name: "Madurese", flag: "🌍" },
  { code: "mai", name: "Maithili", flag: "🇮🇳" },
  { code: "mak", name: "Makassar", flag: "🌍" },
  { code: "mg", name: "Malagasy", flag: "🇲🇬" },
  { code: "ms", name: "Malay", flag: "🇲🇾" },
  { code: "ms-Arab", name: "Malay (Jawi)", flag: "🌍" },
  { code: "ml", name: "Malayalam", flag: "🇮🇳" },
  { code: "mt", name: "Maltese", flag: "🇲🇹" },
  { code: "mam", name: "Mam", flag: "🌍" },
  { code: "gv", name: "Manx", flag: "🌍" },
  { code: "mi", name: "Maori", flag: "🇳🇿" },
  { code: "mr", name: "Marathi", flag: "🇮🇳" },
  { code: "mh", name: "Marshallese", flag: "🌍" },
  { code: "mwr", name: "Marwadi", flag: "🌍" },
  { code: "mfe", name: "Mauritian Creole", flag: "🌍" },
  { code: "mhr", name: "Meadow Mari", flag: "🌍" },
  { code: "mni", name: "Meiteilon (Manipuri)", flag: "🇮🇳" },
  { code: "min", name: "Minang", flag: "🌍" },
  { code: "lus", name: "Mizo", flag: "🇮🇳" },
  { code: "mn", name: "Mongolian", flag: "🇲🇳" },
  { code: "my", name: "Myanmar (Burmese)", flag: "🇲🇲" },
  { code: "nhe", name: "Nahuatl (Eastern Huasteca)", flag: "🌍" },
  { code: "ndc", name: "Ndau", flag: "🌍" },
  { code: "nr", name: "Ndebele (South)", flag: "🌍" },
  { code: "new", name: "Nepalbhasa (Newari)", flag: "🌍" },
  { code: "ne", name: "Nepali", flag: "🇳🇵" },
  { code: "nqo", name: "NKo", flag: "🌍" },
  { code: "no", name: "Norwegian", flag: "🇳🇴" },
  { code: "nus", name: "Nuer", flag: "🌍" },
  { code: "oc", name: "Occitan", flag: "🌍" },
  { code: "or", name: "Odia (Oriya)", flag: "🇮🇳" },
  { code: "om", name: "Oromo", flag: "🇪🇹" },
  { code: "os", name: "Ossetian", flag: "🌍" },
  { code: "pag", name: "Pangasinan", flag: "🌍" },
  { code: "pap", name: "Papiamento", flag: "🌍" },
  { code: "ps", name: "Pashto", flag: "🇦🇫" },
  { code: "fa", name: "Persian", flag: "🇮🇷" },
  { code: "pl", name: "Polish", flag: "🇵🇱" },
  { code: "pt-BR", name: "Portuguese (Brazil)", flag: "🇧🇷" },
  { code: "pt-PT", name: "Portuguese (Portugal)", flag: "🇵🇹" },
  { code: "pa-Guru", name: "Punjabi (Gurmukhi)", flag: "🇮🇳" },
  { code: "pa-Arab", name: "Punjabi (Shahmukhi)", flag: "🇵🇰" },
  { code: "qu", name: "Quechua", flag: "🇵🇪" },
  { code: "kek", name: "Qʼeqchiʼ", flag: "🌍" },
  { code: "rom", name: "Romani", flag: "🌍" },
  { code: "ro", name: "Romanian", flag: "🇷🇴" },
  { code: "rn", name: "Rundi", flag: "🌍" },
  { code: "ru", name: "Russian", flag: "🇷🇺" },
  { code: "se", name: "Sami (North)", flag: "🌍" },
  { code: "sm", name: "Samoan", flag: "🇼🇸" },
  { code: "sg", name: "Sango", flag: "🌍" },
  { code: "sa", name: "Sanskrit", flag: "🇮🇳" },
  { code: "sat-Latn", name: "Santali (Latin)", flag: "🌍" },
  { code: "sat-Olck", name: "Santali (Ol Chiki)", flag: "🌍" },
  { code: "gd", name: "Scots Gaelic", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "nso", name: "Sepedi", flag: "🌍" },
  { code: "sr", name: "Serbian", flag: "🇷🇸" },
  { code: "st", name: "Sesotho", flag: "🇱🇸" },
  { code: "crs", name: "Seychellois Creole", flag: "🌍" },
  { code: "shn", name: "Shan", flag: "🌍" },
  { code: "sn", name: "Shona", flag: "🇿🇼" },
  { code: "scn", name: "Sicilian", flag: "🌍" },
  { code: "szl", name: "Silesian", flag: "🌍" },
  { code: "sd", name: "Sindhi", flag: "🇵🇰" },
  { code: "si", name: "Sinhala", flag: "🇱🇰" },
  { code: "sk", name: "Slovak", flag: "🇸🇰" },
  { code: "sl", name: "Slovenian", flag: "🇸🇮" },
  { code: "so", name: "Somali", flag: "🇸🇴" },
  { code: "es", name: "Spanish", flag: "🇪🇸" },
  { code: "su", name: "Sundanese", flag: "🇮🇩" },
  { code: "sus", name: "Susu", flag: "🌍" },
  { code: "sw", name: "Swahili", flag: "🇰🇪" },
  { code: "ss", name: "Swati", flag: "🌍" },
  { code: "sv", name: "Swedish", flag: "🇸🇪" },
  { code: "ty", name: "Tahitian", flag: "🌍" },
  { code: "tg", name: "Tajik", flag: "🇹🇯" },
  { code: "zgh", name: "Tamazight", flag: "🌍" },
  { code: "zgh-Tfng", name: "Tamazight (Tifinagh)", flag: "🌍" },
  { code: "ta", name: "Tamil", flag: "🇮🇳" },
  { code: "tt", name: "Tatar", flag: "🇷🇺" },
  { code: "te", name: "Telugu", flag: "🇮🇳" },
  { code: "tet", name: "Tetum", flag: "🌍" },
  { code: "th", name: "Thai", flag: "🇹🇭" },
  { code: "bo", name: "Tibetan", flag: "🌍" },
  { code: "ti", name: "Tigrinya", flag: "🇪🇷" },
  { code: "tiv", name: "Tiv", flag: "🌍" },
  { code: "tpi", name: "Tok Pisin", flag: "🌍" },
  { code: "to", name: "Tongan", flag: "🌍" },
  { code: "lua", name: "Tshiluba", flag: "🌍" },
  { code: "ts", name: "Tsonga", flag: "🇿🇦" },
  { code: "tn", name: "Tswana", flag: "🌍" },
  { code: "tcy", name: "Tulu", flag: "🌍" },
  { code: "tum", name: "Tumbuka", flag: "🌍" },
  { code: "tr", name: "Turkish", flag: "🇹🇷" },
  { code: "tk", name: "Turkmen", flag: "🇹🇲" },
  { code: "tyv", name: "Tuvan", flag: "🌍" },
  { code: "tw", name: "Twi", flag: "🌍" },
  { code: "udm", name: "Udmurt", flag: "🌍" },
  { code: "uk", name: "Ukrainian", flag: "🇺🇦" },
  { code: "ur", name: "Urdu", flag: "🇵🇰" },
  { code: "ug", name: "Uyghur", flag: "🇨🇳" },
  { code: "uz", name: "Uzbek", flag: "🇺🇿" },
  { code: "ve", name: "Venda", flag: "🌍" },
  { code: "vec", name: "Venetian", flag: "🌍" },
  { code: "vi", name: "Vietnamese", flag: "🇻🇳" },
  { code: "war", name: "Waray", flag: "🌍" },
  { code: "cy", name: "Welsh", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { code: "wo", name: "Wolof", flag: "🌍" },
  { code: "xh", name: "Xhosa", flag: "🇿🇦" },
  { code: "sah", name: "Yakut", flag: "🌍" },
  { code: "yi", name: "Yiddish", flag: "🇮🇱" },
  { code: "yo", name: "Yoruba", flag: "🇳🇬" },
  { code: "yua", name: "Yucatec Maya", flag: "🌍" },
  { code: "zap", name: "Zapotec", flag: "🌍" },
  { code: "zu", name: "Zulu", flag: "🇿🇦" },
];

/** Options shown in the pre-flight language picker. */
export const PICKER_LANGUAGES: Language[] = [
  ...SUPPORTED_LANGUAGES,
  NATIVE_OPTION,
  { code: "fr-BE", name: "French (Belgium)", flag: "🇧🇪" },
  { code: "de-BE", name: "German (Belgium)", flag: "🇧🇪" },
];
export function getLanguageByCode(code: string): Language | undefined {
  if (code === NATIVE_OPTION.code) return NATIVE_OPTION;
  return PICKER_LANGUAGES.find((lang) => lang.code === code);
}
